on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: PULL REQUEST BUILD FOR Zircon
    timeout-minutes: 60

    runs-on: self-hosted
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          submodules: true
          ssh-key: ${{ secrets.BUILD_KEY }}

      - name: Checkout submodules
        run: git submodule update --init --recursive
